"""add_i
mage_id_to_ai_request_logs

Revision ID: 4036fb055be4
Revises: a0c8e178e15c
Create Date: 2026-01-05 10:29:34.266356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4036fb055be4'
down_revision = 'a0c8e178e15c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_request_logs', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ai_request_logs', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_request_logs', type_='foreignkey')
    op.drop_column('ai_request_logs', 'image_id')
    # ### end Alembic commands ###
